version: '3.1'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file: .env

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file: .env

  ipfs:
    image: ipfs/go-ipfs:latest
    restart: unless-stopped
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ${PWD}/ipfs_staging:/export
      - ${PWD}/ipfs_data:/data/ipfs
    env_file: .env

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8082:8080

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8083:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@me.example.cam
      PGADMIN_DEFAULT_PASSWORD: password


