version: '3.1'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    restart: unless-stopped
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ${PWD}/ipfs_staging:/export
      - ${PWD}/ipfs_data:/data/ipfs
    env_file: .env

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./scripts/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 9087:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password

  catcat-cloud:
    container_name: catcat-cloud
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    environment:
      - PORT=9086
    image: catcatio/catcat-cloud
    working_dir: /usr/app
    ports:
      - "9086:9086"
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    command: npm run dev:docker

volumes:
  pgdata:

