version: '3.1'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    restart: unless-stopped
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ${PWD}/ipfs_staging:/export
      - ${PWD}/ipfs_data:/data/ipfs
    env_file: .env

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8083:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password

volumes:
  pgdata:

